# Generated by Django 5.1 on 2025-10-22 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название филиала')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
                ('department', models.CharField(max_length=100, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фотография')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('internal_phone', models.CharField(max_length=6, unique=True, verbose_name='Внутренний телефон')),
                ('is_smus', models.BooleanField(default=False, verbose_name='Является членом СМУС')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.filial', verbose_name='Филиал')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('direction', models.CharField(choices=[('science', 'Научная деятельность'), ('sport', 'Спортивные мероприятия'), ('culture', 'Культурные мероприятия'), ('education', 'Образовательные мероприятия')], max_length=20, verbose_name='Направление')),
                ('year', models.CharField(default='2024', max_length=4, verbose_name='Год')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='SMUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('predsedatel', 'Председатель'), ('zamestitel', 'Заместитель'), ('chlen', 'Член совета')], max_length=20, verbose_name='Должность в СМУС')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Член СМУС',
                'verbose_name_plural': 'Члены СМУС',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participation', 'Участие (0.1 балла)'), ('curator', 'Кураторство (0.2 балла)'), ('creator', 'Создание (0.3 балла)')], max_length=20, verbose_name='Степень участия')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Участия',
                'unique_together': {('employee', 'event')},
            },
        ),
        migrations.CreateModel(
            name='SMUSRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.event', verbose_name='Мероприятие')),
                ('smus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.smus', verbose_name='Член СМУС')),
            ],
            options={
                'verbose_name': 'Оценка СМУС',
                'verbose_name_plural': 'Оценки СМУС',
                'unique_together': {('smus', 'event')},
            },
        ),
    ]
